/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Data.calculations;
import Data.customermanagement;
import Data.customermanagementDAO;
import Data.validateCustomerMan;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import static sun.net.www.MimeTable.loadTable;

/**
 *
 * @author gal sajja
 */
public class CustomerMan extends javax.swing.JInternalFrame {
    private Vector<Vector<String>> data; 
    private Vector<String> header; 
    /**
     * Creates new form CustomerMan
     */
    public CustomerMan() {
        initComponents();
        jcustid.setText("hint : j1000");
       
        header = new Vector<String>();
        header.add("custID");
        header.add("fname");
        header.add("lname");
        header.add("address");
        header.add("contactno");
        header.add("email");
        loadTable();
    }
    private void loadTable() {

        customermanagementDAO  dao = new customermanagementDAO();
        data = dao.custDetails();

        jcustdetails.setModel(new javax.swing.table.DefaultTableModel(data, header));
        jScrollPane1.setViewportView(jcustdetails);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jcustdetails = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jfname = new javax.swing.JTextField();
        jlname = new javax.swing.JTextField();
        jaddress = new javax.swing.JTextField();
        jcontact = new javax.swing.JTextField();
        jemail = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jcustid = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jdeletebtn = new javax.swing.JButton();
        jupdatebtn = new javax.swing.JButton();
        jinsertbtn = new javax.swing.JButton();
        jclearbtn = new javax.swing.JButton();
        jreportbtn = new javax.swing.JButton();
        jsearchlbl = new javax.swing.JLabel();
        jsearch = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jqty1 = new javax.swing.JTextField();
        jqty2 = new javax.swing.JTextField();
        jqty3 = new javax.swing.JTextField();
        jqty4 = new javax.swing.JTextField();
        jqty5 = new javax.swing.JTextField();
        jqty6 = new javax.swing.JTextField();
        jqty7 = new javax.swing.JTextField();
        jprice1 = new javax.swing.JTextField();
        jprice2 = new javax.swing.JTextField();
        jprice3 = new javax.swing.JTextField();
        jprice4 = new javax.swing.JTextField();
        jprice5 = new javax.swing.JTextField();
        jprice6 = new javax.swing.JTextField();
        jprice7 = new javax.swing.JTextField();
        jamnt1 = new javax.swing.JTextField();
        jamnt2 = new javax.swing.JTextField();
        jamnt3 = new javax.swing.JTextField();
        jamnt4 = new javax.swing.JTextField();
        jamnt5 = new javax.swing.JTextField();
        jamnt6 = new javax.swing.JTextField();
        jamnt7 = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jButton27 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jtotamt = new javax.swing.JTextField();
        jButton28 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Customer Management");
        setPreferredSize(new java.awt.Dimension(1085, 571));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Customer", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Adobe Arabic", 1, 24), new java.awt.Color(0, 51, 255))); // NOI18N

        jcustdetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Customer Name", "Address", "Contact No", "E mail"
            }
        ));
        jcustdetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcustdetailsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jcustdetails);

        jLabel2.setText("First Name");

        jLabel3.setText("Last Name");

        jLabel4.setText("Address");

        jLabel5.setText("Contact No");

        jLabel6.setText("E-mali");

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Customer ID");

        jcustid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jcustidFocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jcustid, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcustid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jdeletebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        jdeletebtn.setText("Delete");
        jdeletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdeletebtnActionPerformed(evt);
            }
        });

        jupdatebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update.png"))); // NOI18N
        jupdatebtn.setText("Update");
        jupdatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jupdatebtnActionPerformed(evt);
            }
        });

        jinsertbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/insert.png"))); // NOI18N
        jinsertbtn.setText("Insert");
        jinsertbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jinsertbtnActionPerformed(evt);
            }
        });

        jclearbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clean.png"))); // NOI18N
        jclearbtn.setText("Clear");
        jclearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jclearbtnActionPerformed(evt);
            }
        });

        jreportbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/report.png"))); // NOI18N
        jreportbtn.setText("Report");
        jreportbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jreportbtnActionPerformed(evt);
            }
        });

        jsearchlbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Search.png"))); // NOI18N
        jsearchlbl.setText("   Search");
        jsearchlbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jsearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jsearchFocusGained(evt);
            }
        });
        jsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jsearchKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jsearchKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jclearbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addComponent(jsearchlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jinsertbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jupdatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jsearch))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdeletebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jreportbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jreportbtn)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jsearchlbl)
                            .addComponent(jsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jclearbtn)
                    .addComponent(jdeletebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jinsertbtn)
                    .addComponent(jupdatebtn))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(25, 25, 25)
                            .addComponent(jemail, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(25, 25, 25)
                            .addComponent(jcontact))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(25, 25, 25)
                            .addComponent(jaddress))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(25, 25, 25)
                            .addComponent(jlname))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(25, 25, 25)
                            .addComponent(jfname)))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(15, 15, 15)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jfname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jlname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jcontact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Customer Details", jPanel1);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Invoice", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Adobe Arabic", 1, 24), new java.awt.Color(0, 51, 255))); // NOI18N

        jLabel8.setText("Invoice No");

        jLabel9.setText("Customer Name");

        jLabel10.setText("Address");

        jLabel12.setText("Date");

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255)));

        jLabel16.setText("                           Description");

        jLabel17.setText("       Qty");

        jLabel18.setText("          Price(Rs)");

        jLabel19.setText("         Amount(Rs)");

        jprice1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jprice1KeyReleased(evt);
            }
        });

        jprice2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jprice2KeyReleased(evt);
            }
        });

        jprice3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jprice3KeyReleased(evt);
            }
        });

        jprice4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jprice4KeyReleased(evt);
            }
        });

        jprice5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jprice5KeyReleased(evt);
            }
        });

        jprice6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jprice6KeyReleased(evt);
            }
        });

        jprice7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jprice7KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextField15, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                    .addComponent(jTextField16)
                    .addComponent(jTextField17, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField18, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField19, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField20, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField21, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                    .addComponent(jqty1)
                    .addComponent(jqty2)
                    .addComponent(jqty3)
                    .addComponent(jqty4)
                    .addComponent(jqty5)
                    .addComponent(jqty6)
                    .addComponent(jqty7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                    .addComponent(jprice1)
                    .addComponent(jprice2)
                    .addComponent(jprice3)
                    .addComponent(jprice4)
                    .addComponent(jprice5)
                    .addComponent(jprice6)
                    .addComponent(jprice7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jamnt1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jamnt2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jamnt3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jamnt4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jamnt5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jamnt6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jamnt7, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jqty1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jprice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jamnt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jqty2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jprice2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jamnt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jqty3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jprice3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jamnt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jqty4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jprice4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jamnt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jqty5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jprice5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jamnt5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jqty6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jprice6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jamnt6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jqty7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jprice7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jamnt7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 65, Short.MAX_VALUE))
        );

        jPanel13.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/insert.png"))); // NOI18N
        jButton27.setText("Create");
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });

        jButton30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/report.png"))); // NOI18N
        jButton30.setText("Report");
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton30, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton27, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jButton27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(11, 11, 11)
                .addComponent(jButton30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/totalAmount.png"))); // NOI18N
        jButton28.setText("Total Amount(Rs)");
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField12, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                            .addComponent(jTextField10)
                            .addComponent(jTextField8)
                            .addComponent(jTextField9))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 194, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtotamt, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(78, 78, 78)
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtotamt)
                            .addComponent(jButton28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Create Bill", jPanel2);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        // TODO add your handling code here:
        //        if(!jqty1.equals(""));
    int q1 = 0;
    int q2 = 0;
    int q3 = 0;
    int q4 = 0;
    int q5 = 0;
    int q6 = 0;
    int q7 = 0;
    
    float price1 = 0;
    float price2 = 0;
    float price3 = 0;
    float price4 = 0;
    float price5 = 0;
    float price6 = 0;
    float price7 = 0;
    
        if(!jqty1.getText().equals("")){
        q1 = Integer.parseInt(jqty1.getText());
        }
        if(!jqty2.getText().equals("")){
        q2 = Integer.parseInt(jqty2.getText());
        }
        if(!jqty3.getText().equals("")){
        q3 = Integer.parseInt(jqty3.getText());
        }
        if(!jqty4.getText().equals("")){
        q4 = Integer.parseInt(jqty4.getText());
        }
        if(!jqty5.getText().equals("")){
        q5 = Integer.parseInt(jqty5.getText());
        }
        if(!jqty6.getText().equals("")){
        q6 = Integer.parseInt(jqty6.getText());
        }
        if(!jqty7.getText().equals("")){
        q7 = Integer.parseInt(jqty7.getText());
        }
        
        if(!jprice1.getText().equals("")){
        price1 = Float.parseFloat(jprice1.getText());
        }
        if(!jprice2.getText().equals("")){
        price2 = Float.parseFloat(jprice2.getText());
        }
        if(!jprice3.getText().equals("")){
        price3 = Float.parseFloat(jprice3.getText());
        }
        if(!jprice4.getText().equals("")){
        price4 = Float.parseFloat(jprice4.getText());
        }
        if(!jprice5.getText().equals("")){
        price5 = Float.parseFloat(jprice5.getText());
        }
        if(!jprice6.getText().equals("")){
        price6 = Float.parseFloat(jprice6.getText());
        }
        if(!jprice7.getText().equals("")){
        price7 = Float.parseFloat(jprice7.getText());
        }
        
        
        customermanagement bill = new customermanagement(q1,q2,q3,q4,q5,q6,q7,price1,price2,price3,price4,price5,price6,price7);
        calculations calc = new calculations();
        float tot = calc.calc(bill);
        
       
        jtotamt.setText(Float.toString(tot));
      
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jdeletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdeletebtnActionPerformed
        // TODO add your handling code here:
        customermanagement cust = new customermanagement(jcustid.getText());

        customermanagementDAO dao = new customermanagementDAO();

        if(jcustid.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please select a row", "Warning", 0);
        }

        else{

            int decision = JOptionPane.showConfirmDialog(this, "Do you really want to delete this record?", "Warning", 0);
            if(decision == 0){

                boolean result = dao.deleteRecord(cust);

                if(result==true){
                    JOptionPane.showMessageDialog(this, "Succesfully Deleted");
                    loadTable();
                    jcustid.setText(null);
                    jfname.setText(null);
                    jlname.setText(null);
                    jaddress.setText(null);
                    jcontact.setText(null);
                    jemail.setText(null);

                }
                else{
                    JOptionPane.showMessageDialog(this, "No record detected!", "Error", 0);
                }
            }
        }

    }//GEN-LAST:event_jdeletebtnActionPerformed

    private void jupdatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jupdatebtnActionPerformed
        // TODO add your handling code here:

        customermanagement cust = new customermanagement(jcustid.getText() , jfname.getText(),jlname.getText(),jaddress.getText(),Integer.parseInt(jcontact.getText()),jemail.getText());
        validateCustomerMan val = new validateCustomerMan();
        boolean id = val.validatecustId(jcustid.getText());
        boolean fname = val.validateFname(jfname.getText());
        boolean lname = val.validateLname(jlname.getText());
        boolean address = val.validateAddress(jaddress.getText());
        boolean contact = val.validatecontact(jcontact.getText());
        boolean email = val.validateemail(jemail.getText());

        if(id==false){
            JOptionPane.showMessageDialog(this, "Invalid ID! \nID length should be 4 and first letter should\nstart with j \nex : j100");
        }
        else if(fname==false){
            JOptionPane.showMessageDialog(this, "Please fill First Name!");
        }
        else if(lname==false){
            JOptionPane.showMessageDialog(this, "Please fill Last Name!");
        }
        else if(address==false){
            JOptionPane.showMessageDialog(this, "Please fill Address!");
        }
        else if(contact==false){
            JOptionPane.showMessageDialog(this, "Invalid number!\nPlease enter again\nex : 0711234567");
        }
        else if(email==false){
            JOptionPane.showMessageDialog(this, "Enter the email correctly!");
        }
        else{
            customermanagementDAO dao = new customermanagementDAO();
            boolean result = dao.updateRecord(cust);

            if(result == true){
                JOptionPane.showMessageDialog(this, "Succesfully Updated");
                loadTable();
                jcustid.setText(null);
                jfname.setText(null);
                jlname.setText(null);
                jaddress.setText(null);
                jcontact.setText(null);
                jemail.setText(null);

            }
            else{
                JOptionPane.showMessageDialog(this, "You didn't update anything!");
            }

        }
    }//GEN-LAST:event_jupdatebtnActionPerformed

    private void jinsertbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jinsertbtnActionPerformed
        // TODO add your handling code here:
        validateCustomerMan val = new validateCustomerMan();

        if(jcontact.getText().equals("")==true)
        {
            JOptionPane.showMessageDialog(this, "please enter the contact number!");
        }
        else{

            boolean id = val.validatecustId(jcustid.getText());
            boolean fname = val.validateFname(jfname.getText());
            boolean lname = val.validateLname(jlname.getText());
            boolean address = val.validateAddress(jaddress.getText());
            boolean contact = val.validatecontact(jcontact.getText());
            boolean email = val.validateemail(jemail.getText());

            if(id==false){
                JOptionPane.showMessageDialog(this, "Invalid ID! \nID length should be 4 and first letter should\nstart with j \nex : j100");
            }
            else if(fname==false){
                JOptionPane.showMessageDialog(this, "Please fill First Name!");
            }
            else if(lname==false){
                JOptionPane.showMessageDialog(this, "Please fill Last Name!");
            }
            else if(address==false){
                JOptionPane.showMessageDialog(this, "Please fill Address!");
            }
            else if(contact==false){
                JOptionPane.showMessageDialog(this, "Invalid number!\nPlease enter again\nex : 0711234567");
            }
            else if(email==false){
                JOptionPane.showMessageDialog(this, "Enter the email correctly!");
            }
            else{
                customermanagement cust = new customermanagement(jcustid.getText() , jfname.getText(),jlname.getText(),jaddress.getText(), Integer.parseInt(jcontact.getText()) , jemail.getText());

                customermanagementDAO dao = new customermanagementDAO();
                boolean result = dao.addRecord(cust);

                if(result == true){
                    JOptionPane.showMessageDialog(this, "Succesfully Inserted");
                    loadTable();
                    jcustid.setText(null);
                    jfname.setText(null);
                    jlname.setText(null);
                    jaddress.setText(null);
                    jcontact.setText(null);
                    jemail.setText(null);

                }
                else{
                    JOptionPane.showMessageDialog(this, "Customer ID is already exist. Please enter valid one!");
                }
            }
        }

    }//GEN-LAST:event_jinsertbtnActionPerformed

    private void jclearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jclearbtnActionPerformed
        // TODO add your handling code here:
        jcustid.setText(null);
        jfname.setText(null);
        jlname.setText(null);
        jaddress.setText(null);
        jcontact.setText(null);
        jemail.setText(null);
        jsearch.setText(null);
        loadTable();
    }//GEN-LAST:event_jclearbtnActionPerformed

    private void jreportbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jreportbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jreportbtnActionPerformed

    private void jsearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jsearchFocusGained
        // TODO add your handling code here:
        if(jsearch.getText().equals("hint : \"colombo\" , \"saman \", \"c0001\"" )){
            jsearch.setText(null);
        }

    }//GEN-LAST:event_jsearchFocusGained

    private void jsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jsearchKeyReleased
        // TODO add your handling code here:
        //         customermanagementDAO  dao = new customermanagementDAO();
        //        data = dao.custDetails();
        //
        //        jcustdetails.setModel(new javax.swing.table.DefaultTableModel(data, header));
        //        jScrollPane1.setViewportView(jcustdetails);

        customermanagementDAO dao = new customermanagementDAO();
        data = dao.searchcustdetails(jsearch.getText());
        jcustdetails.setModel(new javax.swing.table.DefaultTableModel(data, header));
        jScrollPane1.setViewportView(jcustdetails);
    }//GEN-LAST:event_jsearchKeyReleased

    private void jsearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jsearchKeyTyped
        // TODO add your handling code here:
        //        customermanagementDAO dao = new customermanagementDAO();
        //        data= dao.searchcustdetails(jsearch.getText());
        //        jcustdetails.setModel(new javax.swing.table.DefaultTableModel(data, header));
        //        jScrollPane1.setViewportView(jcustdetails);
    }//GEN-LAST:event_jsearchKeyTyped

    private void jprice1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jprice1KeyReleased
        // TODO add your handling code here:
            int quantity1 = Integer.parseInt(jqty1.getText());
            float price1 = Float.parseFloat(jprice1.getText());
            
            float amount1 = quantity1*price1;
            jamnt1.setText(Float.toString(amount1));
    }//GEN-LAST:event_jprice1KeyReleased

    private void jprice2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jprice2KeyReleased
        // TODO add your handling code here:
            int quantity2 = Integer.parseInt(jqty2.getText());
            float price2 = Float.parseFloat(jprice2.getText());
            
            float amount2 = quantity2*price2;
            jamnt2.setText(Float.toString(amount2));
    }//GEN-LAST:event_jprice2KeyReleased

    private void jprice3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jprice3KeyReleased
        // TODO add your handling code here:
        int quantity3 = Integer.parseInt(jqty3.getText());
        float price3 = Float.parseFloat(jprice3.getText());
        
        float amount3 = quantity3*price3;
        jamnt3.setText(Float.toString(amount3));
    }//GEN-LAST:event_jprice3KeyReleased

    private void jprice4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jprice4KeyReleased
        // TODO add your handling code here:
        int quantity4 = Integer.parseInt(jqty4.getText());
        float price4  = Float.parseFloat(jprice4.getText());
        
        float amount4 = quantity4*price4;
        jamnt4.setText(Float.toString(amount4));
    }//GEN-LAST:event_jprice4KeyReleased

    private void jprice5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jprice5KeyReleased
        // TODO add your handling code here:
        int quantity5 = Integer.parseInt(jqty5.getText());
        float price5  = Float.parseFloat(jprice5.getText());
        
        float amount5 = quantity5*price5;
        jamnt5.setText(Float.toString(amount5));
    }//GEN-LAST:event_jprice5KeyReleased

    private void jprice6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jprice6KeyReleased
        // TODO add your handling code here:
        int quantity6 = Integer.parseInt(jqty6.getText());
        float price6  = Float.parseFloat(jprice6.getText());
        
        float amount6 = quantity6*price6;
        jamnt6.setText(Float.toString(amount6));
    }//GEN-LAST:event_jprice6KeyReleased

    private void jprice7KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jprice7KeyReleased
        // TODO add your handling code here:
        int quantity7 = Integer.parseInt(jqty7.getText());
        float price7  = Float.parseFloat(jprice7.getText());
        
        float amount7 = quantity7*price7;
        jamnt7.setText(Float.toString(amount7));
    }//GEN-LAST:event_jprice7KeyReleased

    private void jcustdetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcustdetailsMouseClicked
        // TODO add your handling code here:
        customermanagementDAO cust = new customermanagementDAO();
        
        try{
            int row = jcustdetails.getSelectedRow();
            String tableClick = (jcustdetails.getModel().getValueAt(row, 0).toString());
            String sql = "select * from `airconditionmanagementsystem`.`customer` where `customer`.`custID` = '"+tableClick+"'";
            
            Connection db = cust.tableToTextField();
            PreparedStatement pst = db.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                String txt1 = rs.getString("custID");
                jcustid.setText(txt1);
                String txt2 = rs.getString("fname");
                jfname.setText(txt2);
                String txt3 = rs.getString("lname");
                jlname.setText(txt3);
                String txt4 = rs.getString("address");
                jaddress.setText(txt4);
                String txt5 = rs.getString("contact");
                jcontact.setText(txt5);
                String txt6 = rs.getString("email");
                jemail.setText(txt6);

            }
            
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jcustdetailsMouseClicked

    private void jcustidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jcustidFocusGained
        // TODO add your handling code here:
        if(jcustid.getText().equals("hint : j1000")){
            jcustid.setText(null);
        }
    }//GEN-LAST:event_jcustidFocusGained

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton30;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField jaddress;
    private javax.swing.JTextField jamnt1;
    private javax.swing.JTextField jamnt2;
    private javax.swing.JTextField jamnt3;
    private javax.swing.JTextField jamnt4;
    private javax.swing.JTextField jamnt5;
    private javax.swing.JTextField jamnt6;
    private javax.swing.JTextField jamnt7;
    private javax.swing.JButton jclearbtn;
    private javax.swing.JTextField jcontact;
    private javax.swing.JTable jcustdetails;
    private javax.swing.JTextField jcustid;
    private javax.swing.JButton jdeletebtn;
    private javax.swing.JTextField jemail;
    private javax.swing.JTextField jfname;
    private javax.swing.JButton jinsertbtn;
    private javax.swing.JTextField jlname;
    private javax.swing.JTextField jprice1;
    private javax.swing.JTextField jprice2;
    private javax.swing.JTextField jprice3;
    private javax.swing.JTextField jprice4;
    private javax.swing.JTextField jprice5;
    private javax.swing.JTextField jprice6;
    private javax.swing.JTextField jprice7;
    private javax.swing.JTextField jqty1;
    private javax.swing.JTextField jqty2;
    private javax.swing.JTextField jqty3;
    private javax.swing.JTextField jqty4;
    private javax.swing.JTextField jqty5;
    private javax.swing.JTextField jqty6;
    private javax.swing.JTextField jqty7;
    private javax.swing.JButton jreportbtn;
    private javax.swing.JTextField jsearch;
    private javax.swing.JLabel jsearchlbl;
    private javax.swing.JTextField jtotamt;
    private javax.swing.JButton jupdatebtn;
    // End of variables declaration//GEN-END:variables
}
